# Generated by Django 3.2.6 on 2021-09-01 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitemstatus',
            old_name='order_item_status',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='orderitemstatus',
            name='order_item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_item_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderitemstatus'),
        ),
    ]
